In [ ]:
import pandas as pd

In [ ]:
Crop_Land_Nutrient_Balance_df= pd.read_csv("Crop_Land_Nutrient_Balance.csv")
Crop_Land_Nutrient_Balance_df.drop(['Domain','Domain Code', 'Area Code (M49)', 'Element Code','Item Code', 'Year Code', 'Note'], axis=1,inplace=True)
Crop_Land_Nutrient_Balance_df.rename(columns={'Element': 'Nutrients', 'Item': 'Nutrients_type', 'Value': 'Nutrients_Value',  'Unit': 'Nutrients_Unit', 'Flag': 'Nutrients_Flag', 'Flag Description': 'Nutrients_Flag_Description'}, inplace=True)
Crop_Land_Nutrient_Balance_df = Crop_Land_Nutrient_Balance_df[Crop_Land_Nutrient_Balance_df['Nutrients'].isin(['Cropland nitrogen', 'Cropland phosphorus', 'Cropland potassium'])]
Crop_Land_Nutrient_Balance_df = Crop_Land_Nutrient_Balance_df[Crop_Land_Nutrient_Balance_df['Year'].between(2000, 2021)]
# print(Crop_Land_Nutrient_Balance_df['Nutrients'].unique())
Crop_Land_Nutrient_Balance_df

FileNotFoundError: [Errno 2] No such file or directory: 'Crop_Land_Nutrient_Balance.csv'

In [ ]:
Crop_Production_df= pd.read_csv("Crop_Production.csv")
Crop_Production_df.drop(['Domain','Domain Code', 'Area Code (M49)', 'Element Code','Item Code (CPC)', 'Year Code' , 'Note'], axis=1,inplace=True)
Crop_Production_df.rename(columns={'Element': 'Prod_type', 'Value': 'Prod_Value', 'Item': 'Crop_Name', 'Value': 'Crop_Production_Value',  'Unit': 'Crop_Production_Unit', 'Flag': 'Crop_Production_Flag', 'Flag Description': 'Crop_Production_Flag_Description'}, inplace=True)
Crop_Production_df = Crop_Production_df[Crop_Production_df['Year'].between(2000, 2021)]
# Crop_Production_df = Crop_Land_Nutrient_Balance_df[Crop_Land_Nutrient_Balance_df['Nutrients'].isin(['Cropland nitrogen', 'Cropland phosphorus', 'Cropland potassium'])]
# print(Crop_Land_Nutrient_Balance_df['Nutrients'].unique())
Crop_Production_df

,Area,Prod_type,Crop_Name,Year,Crop_Production_Unit,Crop_Production_Value,Crop_Production_Flag,Crop_Production_Flag_Description
117,Bangladesh,Area harvested,Barley,2000,ha,6880.00,A,Official figure
118,Bangladesh,Yield,Barley,2000,100 g/ha,7267.00,A,Official figure
119,Bangladesh,Production,Barley,2000,t,5000.00,A,Official figure
120,Bangladesh,Area harvested,Barley,2001,ha,5668.00,A,Official figure
121,Bangladesh,Yield,Barley,2001,100 g/ha,7057.00,A,Official figure
...,...,...,...,...,...,...,...,...
2848,Viet Nam,Yield,Sugar cane,2020,100 g/ha,622030.00,A,Official figure
2849,Viet Nam,Production,Sugar cane,2020,t,11534588.71,A,Official figure
2850,Viet Nam,Area harvested,Sugar cane,2021,ha,165919.00,A,Official figure
2851,Viet Nam,Yield,Sugar cane,2021,100 g/ha,647355.00,A,Official figure
2852,Viet Nam,Production,Sugar cane,2021,t,10740873.28,A,Official figure

In [ ]:
Temperature_Change_On_Land_df= pd.read_csv("Temperature_Change_On_Land.csv")
Temperature_Change_On_Land_df.drop(['Domain','Domain Code', 'Area Code (M49)', 'Element Code', 'Months Code', 'Year Code'],  axis=1,inplace=True)
Temperature_Change_On_Land_df.rename(columns={'Element': 'Temp_Change', 'Value': 'TMP_Value',  'Unit': 'TMP_Unit', 'Flag': 'TMP_Flag', 'Flag Description': 'TMP_Description'}, inplace=True)
Temperature_Change_On_Land_df = Temperature_Change_On_Land_df[Temperature_Change_On_Land_df['Year'].between(2000, 2021)]
Temperature_Change_On_Land_df = Temperature_Change_On_Land_df[Temperature_Change_On_Land_df['Months'].isin(['January','February','March' ,'April' ,'May' ,'June','July','August','September','October','November','December'])]
# print(Temperature_Change_On_Land_df['Months'].unique())
Temperature_Change_On_Land_df

,Area,Temp_Change,Months,Year,TMP_Unit,TMP_Value,TMP_Flag,TMP_Description
39,Bangladesh,Temperature change,January,2000,°c,0.532,E,Estimated value
40,Bangladesh,Temperature change,January,2001,°c,-0.388,E,Estimated value
41,Bangladesh,Temperature change,January,2002,°c,0.832,E,Estimated value
42,Bangladesh,Temperature change,January,2003,°c,-1.236,E,Estimated value
43,Bangladesh,Temperature change,January,2004,°c,-0.055,E,Estimated value
...,...,...,...,...,...,...,...,...
9914,Viet Nam,Standard Deviation,December,2017,°c,0.944,E,Estimated value
9915,Viet Nam,Standard Deviation,December,2018,°c,0.944,E,Estimated value
9916,Viet Nam,Standard Deviation,December,2019,°c,0.944,E,Estimated value
9917,Viet Nam,Standard Deviation,December,2020,°c,0.944,E,Estimated value
9918,Viet Nam,Standard Deviation,December,2021,°c,0.944,E,Estimated value

In [ ]:
Land_Use_df= pd.read_csv("Land_Use.csv")
Land_Use_df.drop([ 'Domain','Domain Code', 'Area Code (M49)', 'Element Code', 'Item Code', 'Year Code', 'Note'],  axis=1,inplace=True)
Land_Use_df.rename(columns={'Item': 'Area_type','Value':'Area Value', 'Element': 'Land_Use_Element', 'Unit': 'Land_Use_Unit', 'Flag': 'Land_Use_Flag', 'Flag Description': 'Land_Use_Flag_Description'}, inplace=True)
Land_Use_df = Land_Use_df[Land_Use_df['Year'].between(2000, 2021)]
Land_Use_df = Land_Use_df[Land_Use_df['Area_type'].isin(['Agricultural land','Cropland','Arable land'])]
# print(Land_Use_df['Area_type'].unique())
Land_Use_df

,Area,Land_Use_Element,Area_type,Year,Land_Use_Unit,Area Value,Land_Use_Flag,Land_Use_Flag_Description
100,Bangladesh,Area,Agricultural land,2000,1000 ha,9400.00,I,Imputed value
101,Bangladesh,Area,Agricultural land,2001,1000 ha,9403.00,I,Imputed value
102,Bangladesh,Area,Agricultural land,2002,1000 ha,9353.00,I,Imputed value
103,Bangladesh,Area,Agricultural land,2003,1000 ha,9328.00,I,Imputed value
104,Bangladesh,Area,Agricultural land,2004,1000 ha,9323.00,I,Imputed value
...,...,...,...,...,...,...,...,...
3294,Viet Nam,Share in Agricultural land,Arable land,2019,%,54.76,E,Estimated value
3295,Viet Nam,Area,Arable land,2020,1000 ha,6787.00,A,Official figure
3296,Viet Nam,Share in Agricultural land,Arable land,2020,%,54.91,E,Estimated value
3297,Viet Nam,Area,Arable land,2021,1000 ha,6787.00,I,Imputed value
3298,Viet Nam,Share in Agricultural land,Arable land,2021,%,54.91,E,Estimated value

In [ ]:
Emission_Total_df= pd.read_csv("Emission_Total.csv")
Emission_Total_df.drop(['Domain','Domain Code', 'Area Code (M49)', 'Element Code', 'Item Code (CPC)', 'Year Code',
       'Source Code', 'Source', 'Note'],  axis=1,inplace=True)
Emission_Total_df.rename(columns={'Element': 'Emissions','Value': "Emission_Value",'Item':'Crop_Name', 'Value': 'Emission_Total_Value',  'Unit': 'Emission_Total_Unit', 'Flag': 'Emission_Total_Flag', 'Flag Description': 'Emission_Total_Flag_Description'}, inplace=True)
Emission_Total_df = Emission_Total_df[Emission_Total_df['Year'].between(2000, 2021)]
Emission_Total_df= Emission_Total_df[Emission_Total_df['Emissions'].isin(['Crops total (Emissions N2O)' ,'Crop residues (N content)','Crops total (Emissions CH4)'])]
# print(Emission_Total_df['Emissions'].unique())
Emission_Total_df

,Area,Emissions,Crop_Name,Year,Emission_Total_Unit,Emission_Total_Value,Emission_Total_Flag,Emission_Total_Flag_Description
195,Bangladesh,Crops total (Emissions N2O),Barley,2000,kt,1.700000e-03,E,Estimated value
196,Bangladesh,Crop residues (N content),Barley,2000,kg,9.069507e+04,E,Estimated value
200,Bangladesh,Crops total (Emissions N2O),Barley,2001,kt,1.400000e-03,E,Estimated value
201,Bangladesh,Crop residues (N content),Barley,2001,kg,7.345336e+04,E,Estimated value
205,Bangladesh,Crops total (Emissions N2O),Barley,2002,kt,1.000000e-03,E,Estimated value
...,...,...,...,...,...,...,...,...
7726,Viet Nam,Crops total (Emissions CH4),Rice,2020,kt,1.285475e+03,E,Estimated value
7727,Viet Nam,Crop residues (N content),Rice,2020,kg,4.691392e+08,E,Estimated value
7736,Viet Nam,Crops total (Emissions N2O),Rice,2021,kt,9.470100e+00,E,Estimated value
7737,Viet Nam,Crops total (Emissions CH4),Rice,2021,kt,1.285011e+03,E,Estimated value
7738,Viet Nam,Crop residues (N content),Rice,2021,kg,4.775130e+08,E,Estimated value

In [ ]:
Value_of_Agricultural_Production_df= pd.read_csv("Value_of_Agricultural_Production.csv")
Value_of_Agricultural_Production_df.drop(['Domain','Domain Code', 'Area Code (M49)', 'Element Code', 'Item Code (CPC)', 'Year Code'],  axis=1,inplace=True)
Value_of_Agricultural_Production_df.rename(columns={'Element': 'Production_Value_Type', 'Item': 'Crop_Name', 'Value': 'Production_Value_$', 'Unit': 'Prod_Output_Unit', 'Flag': 'Prod_Output_Flag', 'Flag Description': 'Prod_Output_Flag_Description'}, inplace=True)
Value_of_Agricultural_Production_df = Value_of_Agricultural_Production_df[Value_of_Agricultural_Production_df['Year'].between(2000, 2021)]
Value_of_Agricultural_Production_df= Value_of_Agricultural_Production_df[Value_of_Agricultural_Production_df['Production_Value_Type'].isin(['Gross Production Value (current thousand US$)'])]
# print(Value_of_Agricultural_Production_df['Production_Value_Type'].unique())
Value_of_Agricultural_Production_df

,Area,Production_Value_Type,Crop_Name,Year,Prod_Output_Unit,Production_Value_$,Prod_Output_Flag,Prod_Output_Flag_Description
124,Bangladesh,Gross Production Value (current thousand US$),Barley,2006,1000 USD,154,E,Estimated value
125,Bangladesh,Gross Production Value (current thousand US$),Barley,2007,1000 USD,250,E,Estimated value
342,Bangladesh,Gross Production Value (current thousand US$),Rice,2000,1000 USD,4459731,E,Estimated value
343,Bangladesh,Gross Production Value (current thousand US$),Rice,2001,1000 USD,3918921,E,Estimated value
344,Bangladesh,Gross Production Value (current thousand US$),Rice,2002,1000 USD,4286101,E,Estimated value
...,...,...,...,...,...,...,...,...
3023,Viet Nam,Gross Production Value (current thousand US$),Sugar cane,2017,1000 USD,810942,E,Estimated value
3024,Viet Nam,Gross Production Value (current thousand US$),Sugar cane,2018,1000 USD,713768,E,Estimated value
3025,Viet Nam,Gross Production Value (current thousand US$),Sugar cane,2019,1000 USD,556230,E,Estimated value
3026,Viet Nam,Gross Production Value (current thousand US$),Sugar cane,2020,1000 USD,401071,E,Estimated value
3027,Viet Nam,Gross Production Value (current thousand US$),Sugar cane,2021,1000 USD,412302,E,Estimated value

In [ ]:
# merged_df=[[]]
# merged_df

[[]]

In [ ]:
merged_df = pd.merge(Crop_Production_df, Emission_Total_df, on=['Area', 'Year','Crop_Name'], how='inner')
merged_df = pd.merge(merged_df,Value_of_Agricultural_Production_df, on=['Area', 'Year','Crop_Name'], how='inner')
merged_df = pd.merge(merged_df,Crop_Land_Nutrient_Balance_df, on=['Area', 'Year'], how='inner')
merged_df = pd.merge(merged_df, Temperature_Change_On_Land_df, on=['Area', 'Year'], how='inner')
merged_df = pd.merge(merged_df,Land_Use_df, on=['Area', 'Year'], how='inner')

In [ ]:
merged_df

,Area,Prod_type,Crop_Name,Year,Crop_Production_Unit,Crop_Production_Value,Crop_Production_Flag,Crop_Production_Flag_Description,Emissions,Emission_Total_Unit,...,TMP_Unit,TMP_Value,TMP_Flag,TMP_Description,Land_Use_Element,Area_type,Land_Use_Unit,Area Value,Land_Use_Flag,Land_Use_Flag_Description
0,Bangladesh,Area harvested,Barley,2006,ha,969.00,A,Official figure,Crops total (Emissions N2O),kt,...,°c,0.700,E,Estimated value,Area,Agricultural land,1000 ha,9280.00,I,Imputed value
1,Bangladesh,Area harvested,Barley,2006,ha,969.00,A,Official figure,Crops total (Emissions N2O),kt,...,°c,0.700,E,Estimated value,Area,Cropland,1000 ha,8680.00,A,Official figure
2,Bangladesh,Area harvested,Barley,2006,ha,969.00,A,Official figure,Crops total (Emissions N2O),kt,...,°c,0.700,E,Estimated value,Share in Agricultural land,Cropland,%,93.53,E,Estimated value
3,Bangladesh,Area harvested,Barley,2006,ha,969.00,A,Official figure,Crops total (Emissions N2O),kt,...,°c,0.700,E,Estimated value,Area,Arable land,1000 ha,7880.00,I,Imputed value
4,Bangladesh,Area harvested,Barley,2006,ha,969.00,A,Official figure,Crops total (Emissions N2O),kt,...,°c,0.700,E,Estimated value,Share in Agricultural land,Arable land,%,84.91,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9694075,Viet Nam,Production,Sugar cane,2021,t,10740873.28,A,Official figure,Crops total (Emissions CH4),kt,...,°c,0.944,E,Estimated value,Area,Agricultural land,1000 ha,12360.00,I,Imputed value
9694076,Viet Nam,Production,Sugar cane,2021,t,10740873.28,A,Official figure,Crops total (Emissions CH4),kt,...,°c,0.944,E,Estimated value,Area,Cropland,1000 ha,11718.00,I,Imputed value
9694077,Viet Nam,Production,Sugar cane,2021,t,10740873.28,A,Official figure,Crops total (Emissions CH4),kt,...,°c,0.944,E,Estimated value,Share in Agricultural land,Cropland,%,94.81,E,Estimated value
9694078,Viet Nam,Production,Sugar cane,2021,t,10740873.28,A,Official figure,Crops total (Emissions CH4),kt,...,°c,0.944,E,Estimated value,Area,Arable land,1000 ha,6787.00,I,Imputed value
9694079,Viet Nam,Production,Sugar cane,2021,t,10740873.28,A,Official figure,Crops total (Emissions CH4),kt,...,°c,0.944,E,Estimated value,Share in Agricultural land,Arable land,%,54.91,E,Estimated value

In [ ]:
merged_df.to_csv('Merged_data.csv', index=False)